spring:
  mvc:
    # servlet:
    #   path: /api
    # data:
    #   rest:
    #     base-path: /api
    locale: pt_PT
    locale-resolver: fixed
  messages:
    encoding: UTF-8
  thymeleaf:
    thymeleaf.cache: false
  jackson:
    date-format: yyyy/MM/dd
server:
  port: 8080
  # redirect_port: 8080
  # server.contextPath is now deprecated, use server.servlet.context-path instead
  # servlet:
  #   context-path: /api
# Custom Typed Properties
config-properties:
  graphql-fqdn: 192.168.122.1
  graphql-port: 5001
  graphql-uri: https://${config-properties.graphql-fqdn}:${config-properties.graphql-port}/graphql
  # moke-users:
  #   - admin
  #   - demo
  #   - prod
